@testURL=http://localhost:3000

@id=61959c3ca23f32fd5f6e1c41


### Get all convocatorias
GET {{testURL}}

### Get convocatoria by id
GET {{testURL}}/{{id}}

### Create a new convocatoria
POST {{testURL}}
content-type: application/json

{
    "nombre": "Convocatoria 2",
    "fecha_inicio": "04/25/2015",
    "fecha_fin": "04/25/2015",
    "acta": "loremIpsum"
}

### Update convocatoria by id
PUT {{testURL}}/{{id}}
content-type: application/json

{
    "nombre": "Convocatoria Actualizada!",
    "fecha_inicio": "2021-12-03",
    "fecha_fin": "04/12/2021",
    "acta": "loremIpsum 2"
}

### Update convocatoria by id
DELETE {{testURL}}/{{id}}